package ru.itmo.wp.model.repository.impl;

import ru.itmo.wp.model.database.DatabaseUtils;
import ru.itmo.wp.model.domain.Entity;
import ru.itmo.wp.model.exception.RepositoryException;

import javax.sql.DataSource;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

abstract class BasicRepositoryImpl<T extends Entity> {
    private final DataSource DATA_SOURCE = DatabaseUtils.getDataSource();

    public T find(long id) {
        return find("SELECT * FROM " + getSimpleName() + " WHERE id=?", List.of(Map.entry("id", id)));
    }

    T find(String statementPart, List<Map.Entry<String, Object>> fields) {
        try {
            return findAll(statementPart, fields).get(0);
        } catch (IndexOutOfBoundsException e) {
            return null;
        }
    }

    List<T> findAll(String statementString, List<Map.Entry<String, Object>> fields) {
        List<T> entities = new ArrayList<>();
        try (Connection connection = DATA_SOURCE.getConnection()) {
            try (PreparedStatement statement = connection.prepareStatement(statementString)) {
                setStatement(fields, statement);
                try (ResultSet resultSet = statement.executeQuery()) {
                    T entity;
                    while ((entity = toEntity(statement.getMetaData(), resultSet)) != null) {
                        entities.add(entity);
                    }
                }
            }
        } catch (SQLException e) {
            throw new RepositoryException("Can't find " + getSimpleName() + '.', e);
        }
        return entities;
    }

    public void save(List<Map.Entry<String, Object>> fields, T entity) {
        String format = generateInsertStatement(fields);

        try (Connection connection = DATA_SOURCE.getConnection()) {
            try (PreparedStatement statement = connection.prepareStatement(format, Statement.RETURN_GENERATED_KEYS)) {
                setStatement(fields, statement);
                if (statement.executeUpdate() != 1) {
                    throw new RepositoryException("Can't save " + getSimpleName() + '.');
                } else {
                    ResultSet generatedKeys = statement.getGeneratedKeys();
                    if (generatedKeys.next()) {
                        entity.setId(generatedKeys.getLong(1));
                        entity.setCreationTime(find(entity.getId()).getCreationTime());
                    } else {
                        throw new RepositoryException("Can't save " + getSimpleName() + " [no autogenerated fields].");
                    }
                }
            }
        } catch (SQLException e) {
            throw new RepositoryException("Can't save " + getSimpleName() + '.', e);
        }
    }

    private String generateInsertStatement(List<Map.Entry<String, Object>> fields) {
        StringBuilder builder = new StringBuilder("INSERT INTO `");
        builder.append(getSimpleName());
        builder.append("` (`");
        for (Map.Entry<String, Object> field : fields) {
            builder.append(field.getKey());
            builder.append("`, `");
        }
        builder.append("creationTime`) VALUES (");
        for (int i = 0; i < fields.size(); ++i) {
            builder.append("?, ");
        }
        builder.append("NOW())");
        return builder.toString();
    }

    private void setStatement(List<Map.Entry<String, Object>> fields, PreparedStatement statement) throws SQLException {
        for (int i = 0; i < fields.size(); ++i) {
            Map.Entry<String, Object> entry = fields.get(i);
            if (entry.getKey().substring(entry.getKey().length() - 2).equalsIgnoreCase("id")) {
                statement.setLong(i + 1, (Long) entry.getValue());
            } else {
                statement.setString(i + 1, (String) entry.getValue());
            }
        }
    }

    abstract T toEntity(ResultSetMetaData metaData, ResultSet resultSet) throws SQLException;

    abstract String getSimpleName();
}
